markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "rusty shutter"
# markdown: rdiscount
markdown: kramdown


author: snowdj
atom-baseurl: "http://snowdj.github.io/bs"
baseurl:   http://snowdj.github.io/bs/
url : http://snowdj.github.io/bs/

disqus: "gopherwood"



navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://foto.lhzhang.com
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

